INSERT INTO GENEROS(NOMBRE) VALUES('ACCION');
INSERT INTO GENEROS(NOMBRE) VALUES('COMEDIA');
INSERT INTO GENEROS(NOMBRE) VALUES('DRAMA');
INSERT INTO GENEROS(NOMBRE) VALUES('FANTASIA'); 
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('JUAN ROMAN RIQUELME', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Homenaje_a_Riquelme_%28cropped%29.jpg/450px-Homenaje_a_Riquelme_%28cropped%29.jpg'); 
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Austin Butler', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Austin_Butler_%2852123912556%29.jpg/330px-Austin_Butler_%2852123912556%29.jpg'); 
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula test',1, '2021-01-02' )